namespace kbaidptest
{
    public class ClaimDescription
    {
        private static readonly Dictionary<string, string> _descriptions = new()
        {
            // EIDAS
            { "urn:oid:2.5.4.4", "Surname" },
            { "urn:oid:2.5.4.42", "Given Name" },
            { "urn:oid:2.16.840.1.113730.3.1.241", "Display Name" },
            { "urn:oid:1.3.6.1.5.5.7.9.3", "Gender" },
            { "urn:oid:1.2.752.29.4.13", "National civic registration number/code" },
            { "urn:oid:1.2.752.201.3.15", "A user's previous national civic registration number" },
            { "urn:oid:1.3.6.1.5.5.7.9.1", "Date of birth" },
            { "urn:oid:1.2.752.201.3.8", "Name at the time of birth" },
            { "urn:oid:2.5.4.9", "Street address" },
            { "urn:oid:2.5.4.18", "Post box" },
            { "urn:oid:2.5.4.17", "Postal code" },
            { "urn:oid:2.5.4.7", "Locality" },
            { "urn:oid:2.5.4.6", "Country" },
            { "urn:oid:1.3.6.1.5.5.7.9.2", "Place of birth" },
            { "urn:oid:1.3.6.1.5.5.7.9.4", "Country of citizenship" },
            { "urn:oid:1.3.6.1.5.5.7.9.5", "Country of Residence" },
            { "urn:oid:2.5.4.20", "Telephone number" },
            { "urn:oid:0.9.2342.19200300.100.1.41", "Mobile number" },
            { "urn:oid:0.9.2342.19200300.100.1.3", "E-mail address" },
            { "urn:oid:2.5.4.10", "Organization name" },
            { "urn:oid:2.5.4.11", "Organizational unit name" },
            { "urn:oid:2.5.4.97", "Organizational identifier code" },
            { "urn:oid:1.2.752.201.3.1", "<uid>@<orgnr>" },
            { "urn:oid:1.2.752.201.3.2", "Transaction identifier" },
            { "urn:oid:1.2.752.201.3.3", "Authentication Context Parameters" },
            { "urn:oid:1.2.752.201.3.10", "User certificate" },
            { "urn:oid:1.2.752.201.3.11", "User signature" },
            { "urn:oid:1.2.752.201.3.13", "Authentication server signature" },
            { "urn:oid:1.2.752.201.3.12", "Signature activation data" },
            { "urn:oid:1.2.752.201.3.14", "Sign message digest" },
            { "urn:oid:1.2.752.201.3.4", "Provisional identifier" },
            { "urn:oid:1.2.752.201.3.5", "Provisional identifier persistence indicator" },
            { "urn:oid:1.2.752.201.3.6", "National civic registration number/code binding URI" },
            { "urn:oid:1.2.752.201.3.16", "Mapped national civic registration number" },
            { "urn:oid:1.2.752.201.3.7", "eIDAS uniqueness identifier for natural persons" },
            { "urn:oid:1.2.752.201.3.9", "eIDAS Natural Person Address" },
            { "urn:oid:1.2.752.29.6.2.1", "HSA-ID" },

            // Skolfederation
            { "urn:oid:1.3.6.1.4.1.2428.90.1.5", "Personnummer (norEduPersonNIN)" },
            { "urn:oid:1.2.752.194.10.2.8", "ID-utfärdande land (sisCivicNoNationality)" },
            { "urn:oid:1.3.6.1.4.1.2428.90.1.3", "Födelsedatum (norEduPersonBirthDate) " },
            { "urn:oid:1.3.6.1.4.1.25178.1.2.2", "Kön (schacGender) " },
            { "urn:oid:1.3.6.1.4.1.5923.1.1.1.6", "Användaridentifierare-ePPN (eduPersonPrincipalName)" },
            { "urn:oid:1.2.752.194.10.1.12 ", "Användaridentifierare-SS12000 (sisSchoolPersonSS12kURL)" },
            { "urn:oid:1.2.752.194.10.2.9", "Mellannamn (sisMiddleName)" },
            { "urn:oid:1.2.752.194.10.2.7", "C/o (sisSchoolCareOf)" },
            { "urn:oid:1.2.752.194.10.2.1", "Vårdnadshavarens barn (sisLegalGuardianFor)" },
            { "urn:oid:1.2.752.194.10.2.2", "Årskurs (sisSchoolGrade) " },
            { "urn:oid:1.2.752.194.10.2.10", "Utbildningsform (sisSchoolType) " },
            { "urn:oid:1.3.6.1.4.1.2428.90.1.12", "Utbildningsanordnare (norEduOrgNIN)" },
            { "urn:oid:1.2.752.194.10.2.3", "Förvaltning (sisOrgDepartment) () Flervärt vä" },
            { "urn:oid:1.2.752.194.10.2.4", "Skolenhetskod (sisSchoolUnitCode)" },
            { "urn:oid:1.2.752.194.10.2.11", "Alternativ kod för utbildningsenhet (sisUnitCodeOther)" },
            { "urn:oid:1.2.752.194.10.2.5", "Elev i elevgrupp (sisSchoolCourseStudent)" },
            { "urn:oid:1.2.752.194.10.2.6", "Lärare för elevgrupp (sisSchoolCourseTeacher)" },

            // ADFS
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/implicitupn", "Implicit UPN" },
            { "http://schemas.microsoft.com/ws/2017/04/identity/claims/riskscore", "Risk Score" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress", "E-Mail Address" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", "Given Name" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", "Name" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn", "UPN" },
            { "http://schemas.xmlsoap.org/claims/CommonName", "Common Name" },
            { "http://schemas.xmlsoap.org/claims/EmailAddress", "AD FS 1.x E-Mail Address" },
            { "http://schemas.xmlsoap.org/claims/Group", "Group" },
            { "http://schemas.xmlsoap.org/claims/UPN", "AD FS 1.x UPN" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/role", "Role" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", "Surname" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/privatepersonalidentifier", "PPID" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier", "Name ID" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant", "Authentication time stamp" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod", "Authentication method" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/denyonlysid", "Deny only group SID" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarysid", "Deny only primary SID" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarygroupsid", "Deny only primary group SID" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", "Group SID" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/primarygroupsid", "Primary group SID" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/primarysid", "Primary SID" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname", "Windows account name" },
            { "http://schemas.microsoft.com/2012/01/devicecontext/claims/isregistereduser", "Is Registered User" },
            { "http://schemas.microsoft.com/2012/01/devicecontext/claims/identifier", "Device Identifier" },
            { "http://schemas.microsoft.com/2012/01/devicecontext/claims/registrationid", "Device Registration Identifier" },
            { "http://schemas.microsoft.com/2012/01/devicecontext/claims/displayname", "Device Registration DisplayName" },
            { "http://schemas.microsoft.com/2012/01/devicecontext/claims/ostype", "Device OS type" },
            { "http://schemas.microsoft.com/2012/01/devicecontext/claims/osversion", "Device OS Version" },
            { "http://schemas.microsoft.com/2012/01/devicecontext/claims/ismanaged", "Is Managed Device" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-forwarded-client-ip", "Forwarded Client IP" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-client-application", "Client Application" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-client-user-agent", "Client User Agent" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-client-ip", "Client IP" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-endpoint-absolute-path", "Endpoint Path" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-proxy", "Proxy" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/relyingpartytrustid", "Application Identifier" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/applicationpolicy", "Application policies" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/authoritykeyidentifier", "Authority Key Identifier" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/basicconstraints", "Basic Constraint" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/eku", "Enhanced Key Usage" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/issuer", "Issuer" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/issuername", "Issuer Name" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/keyusage", "Key Usage" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/notafter", "Not After" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/notbefore", "Not Before" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/certificatepolicy", "Certificate Policies" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/rsa", "Public Key" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/rawdata", "Certificate Raw Data" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/san", "Subject Alternative Name" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/serialnumber", "Serial Number" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/signaturealgorithm", "Signature Algorithm" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/subject", "Subject" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/subjectkeyidentifier", "Subject Key Identifier" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/subjectname", "Subject Name" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/certificatetemplateinformation", "V2 Template Name" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/extension/certificatetemplatename", "V1 Template Name" },
            { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/thumbprint", "Thumbprint" },
            { "http://schemas.microsoft.com/2012/12/certificatecontext/field/x509version", "X.509 Version" },
            { "http://schemas.microsoft.com/ws/2012/01/insidecorporatenetwork", "Inside Corporate Network" },
            { "http://schemas.microsoft.com/ws/2012/01/passwordexpirationtime", "Password Expiration Time" },
            { "http://schemas.microsoft.com/ws/2012/01/passwordexpirationdays", "Password Expiration Days" },
            { "http://schemas.microsoft.com/ws/2012/01/passwordchangeurl", "Update Password URL" },
            { "http://schemas.microsoft.com/claims/authnmethodsreferences", "Authentication Methods References" },
            { "http://schemas.microsoft.com/2012/01/requestcontext/claims/client-request-id", "Client Request ID" },
            { "http://schemas.microsoft.com/ws/2013/11/alternateloginid", "Alternate Login ID" },
            { "http://schemas.microsoft.com/ws/2014/01/identity/claims/accountstore", "Account Store" },
            { "http://schemas.microsoft.com/ws/2014/01/identity/claims/anchorclaimtype", "Anchor Claim Type" },
            { "http://schemas.microsoft.com/2014/01/clientcontext/claims/appid", "OAuth Client Id" },
            { "http://schemas.microsoft.com/2014/01/clientcontext/claims/apptype", "OAuth Client Type" },
            { "http://schemas.microsoft.com/2014/09/devicecontext/claims/iscompliant", "Device compliance status" },
            { "http://schemas.microsoft.com/2014/02/deviceusagetime", "Device Usage Time" },
            { "http://schemas.microsoft.com/2014/02/devicecontext/claims/isknown", "Is Known Device" },
            { "http://schemas.microsoft.com/2014/03/psso", "Persistent Single Sign On" },
            { "http://schemas.microsoft.com/2015/09/prt", "Primary Refresh Token" },
            { "http://schemas.microsoft.com/identity/claims/scope", "Scope of access" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsdevicegroup", "Windows device group" },
            { "http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlywindowsdevicegroup", "Windows deny-only device group" },
            { "http://schemas.microsoft.com/2014/09/devicecontext/claims/trusttype", "Device Trust Type" },
            { "http://schemas.microsoft.com/2014/09/requestcontext/claims/userip", "User IP" },
            { "http://schemas.microsoft.com/claims/authnmethodsproviders", "Authentication Methods Provider" },
            { "http://schemas.microsoft.com/2015/12/devicecontext/claims/tokenbindingid1.0", "Token Binding Id" },
            { "http://schemas.microsoft.com/ws/2017/04/identity/claims/multifactorauthenticationinstant", "Multifactor Authentication time stamp" },

            // ITfoxtec
            { "http://schemas.itfoxtec.com/ws/2014/02/identity/claims/saml2nameid", "Name ID" },
            { "http://schemas.itfoxtec.com/ws/2014/02/identity/claims/saml2nameidformat", "Name ID Format" },
            { "http://schemas.itfoxtec.com/ws/2014/02/identity/claims/saml2sessionindex", "Session Index" }
        };

        public string Get(string type)
        {
            return _descriptions.TryGetValue(type, out string? desc) ? desc : "(No description)";
        }
    }
}
